#!/usr/bin/env bash
# Copies build artifacts (icon, social preview, screenshots) from the repo root into docs/assets/
# so the GitHub Pages landing page (docs/index.html) has real images instead of the "pending" fallback.
#
# Screenshots are generated by a separate process (scripts/screenshots.mjs) and may not exist yet
# when the landing page is first built. Re-run this script any time after they land:
#
#   bash docs/assets/sync.sh
#
set -euo pipefail

DEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEST_DIR/../.." && pwd)"

missing=()

copy() {
  local src="$1" name
  name="$(basename "$src")"
  if [ -f "$REPO_ROOT/$src" ]; then
    cp -f "$REPO_ROOT/$src" "$DEST_DIR/$name"
    echo "copied  $src -> docs/assets/$name"
  else
    missing+=("$src")
    echo "MISSING $src (not generated yet)"
  fi
}

copy "assets/icon-512.png"
copy "assets/social-preview.png"
copy "screenshots/glass-regular-dark-hero.png"
copy "screenshots/glass-regular-light-hero.png"
copy "screenshots/glass-clear-hero.png"
copy "screenshots/glass-opaque-layer1-hero.png"
copy "screenshots/glass-regular-dark-palette.png"
copy "screenshots/glass-regular-dark-layer1-palette.png"

if [ "${#missing[@]}" -gt 0 ]; then
  echo
  echo "${#missing[@]} file(s) still missing; the landing page shows a 'Screenshot pending' placeholder for each until they exist and this script is re-run."
  exit 0
fi

echo
echo "All assets present."
